#!/bin/bash

# Get IPs and users
. ./config.sh

./systemcheck gcstart

if [ $? -ne 0 ];
then
  exit 1
fi

# Save the start date/time for gcstop and the server and aircraft start scripts
DATETIME=`date +%Y-%m-%d-%H-%M`
echo $DATETIME >missionstartdt

# Start ROS on aircraft
echo "Initializing aircraft..."
scp missionstartdt $AIRCRAFT_USER@$AIRCRAFT_IP:missionstartdt >/dev/null
scp config.sh $AIRCRAFT_USER@$AIRCRAFT_IP:config.sh >/dev/null
scp rosstart.sh $AIRCRAFT_USER@$AIRCRAFT_IP:rosstart.sh >/dev/null
ssh $AIRCRAFT_USER@$AIRCRAFT_IP "./rosstart.sh" 
sleep 2
echo "${green}Done.${reset}"

echo "Initializing server..."
# Clean up any old files that may still be present from a failed mission
ssh $SERVER_USER@$SERVER_IP "rm *.bag *.mp4 >/dev/null 2>/dev/null" >/dev/null

scp missionstartdt $SERVER_USER@$SERVER_IP:missionstartdt >/dev/null
scp config.sh $SERVER_USER@$SERVER_IP:config.sh >/dev/null
scp serverstart.sh $SERVER_USER@$SERVER_IP:serverstart.sh >/dev/null


# Start QGC in background
nohup ./QGroundControl.AppImage >/dev/null 2>/dev/null &

echo
echo "Press ENTER to exit this window (safe to do while flying)."
read ENTER

exit 0
